apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service
  namespace: tech-store
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
    spec:
      containers:
        - name: sales-service
          image: 216961644624.dkr.ecr.us-east-1.amazonaws.com/sales-service:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: tech-store-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tech-store-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-store-secret
                  key: POSTGRES_PASSWORD
            - name: INVENTORY_URL
              valueFrom:
                configMapKeyRef:
                  name: tech-store-config
                  key: INVENTORY_URL
